### ISSUE TITLE
Missing tag for 0.1.7 and Cocoapods release

### ISSUE THREAD

**Issue by ealymbaev** [unstoppabledomains/resolution-swift#24]
You have changed the version in Readme to 0.1.7, but have not created tag (release) and have not pushed the release to Cocoapods trunk.

**Comment by merenkoff** [comment]
Yes sure. We are working in some small improvement to our lib, I think today it will be done.
Before this please use 0.1.6 version. Sorry for misunderstanding.

**Comment by ealymbaev** [comment]
Got it, thanks.

Also we are having issues with `BigInt` dependency version (the latest version is 5, but you are using version 3). I have created an issue to `EthereumABI` repo for updating its `BigInt` dependency:

https://github.com/shamatar/EthereumABI/issues/2
