### ISSUE TITLE
[Bug] Package not resolving in Xcode

### ISSUE THREAD

**Issue by kcw-grunt** [unstoppabledomains/resolution-swift#28]
## Issue
When trying to resolve the package, the url `https://github.com/unstoppabledomains/resolution-swift` was not found by Xcode in: File > Swift Packages > Add Package Dependency
|Screenshot|
|-----------|
|<img width="1287" alt="Screen Shot 2021-01-22 at 6 56 09 PM" src="https://user-images.githubusercontent.com/2899463/105533184-ab86c580-5ce3-11eb-8522-e0ca7d5b13cc.png">|

**Comment by merenkoff** [comment]
Are you waiting for resolve it via internet?
What error did you got after waiting?

**Comment by merenkoff** [comment]
@kcw-grunt /\

**Comment by kcw-grunt** [comment]
Well it just never resolves just spins...I was seeing a similar issue in one of the packages I recently created.  I just don't 
remember the fix.

**Comment by merenkoff** [comment]
@kcw-grunt we are updated our Library to 0.3.0 version maybe it will fix your problem. Please check it and if it works ping me here.

**Comment by merenkoff** [comment]
<img width="813" alt="Снимок экрана 2021-02-17 в 15 49 11" src="https://user-images.githubusercontent.com/438099/108213449-b6444700-7137-11eb-8f30-ff69a692e319.png">

**Comment by kcw-grunt** [comment]
Yes..you can close this. It is resolving fine.
