### ISSUE TITLE
Warning in project due to incorrect podspec

### ISSUE THREAD

**Issue by ealymbaev** [unstoppabledomains/resolution-swift#38]
Your podspec includes the following line:

`spec.source_files  = "Sources/UnstoppableDomainsResolution/**/*"`

that causes warning in project when included related to `no rule to process file`.

It happens because you include resources and other non-source files into `spec.source_files`. It would be great if you could fix this issue.

**Comment by ealymbaev** [comment]
Any updates on this?

**Comment by bogdan** [comment]
@DeRain can you take a look?

**Comment by merenkoff** [comment]
@ealymbaev  Working on it will include to the next release. We will inform you, sorry for waiting.

**Comment by merenkoff** [comment]
Please try the latest version of our lib 0.3.7.

--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  UnstoppableDomainsResolution (0.3.7) successfully published
 📅  May 20th, 19:34
 🌎  https://cocoapods.org/pods/UnstoppableDomainsResolution
 👍  Tell your friends!
--------------------------------------------------------------------------------

**Comment by ealymbaev** [comment]
@merenkoff updated dependency, no more warnings, nice work, thanks!
