### ISSUE TITLE
Confirming IPFS key is now redunant

### ISSUE THREAD

**Issue by kcw-grunt** [unstoppabledomains/resolution-swift#67]
Prevously we registered a IPFS key for the project.
But the examples suggests that that is no longer needed. 
In other words: 
`"https://mainnet.infura.io/v3/3c25f57353234b1b853e9861050f4817"`
is all that is needed?

**Comment by kcw-grunt** [comment]
@JohnnyJumper ?

**Comment by sammyluo** [comment]
@kcw-grunt sorry for the late reply.

Yes, that is correct.

**Comment by kcw-grunt** [comment]
Ok thanks
